services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    ports: # For attach to debugger
      - "9229:9229"
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://postgres:postgres@db:5432/sidedish
      PORT: 3000
      WEATHER_API_KEY: ddd8087e0618410186a111005240206
      SMTP_USER: AKIAZI2LFBLPWEKD2VLP
      SMTP_PASS: BOiKHi2KzjzX9S49EkAbjRNysECSeAw7PN58HpNF+z4z
      SMTP_HOST: email-smtp.us-east-1.amazonaws.com
      SMTP_PORT: 587

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "sidedish"
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis/redis-stack
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
