services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-dev
    expose:
      - 3000
    ports: # For attach to debugger
      - "9229:9229"
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://postgres:postgres@db:5432/sidedish
      PORT: 3001
      WEATHER_API_KEY: NBSj1GIAB9tOJQs3WFB0nV3grFV5Lblq
    entrypoint: ["npm", "run", "dev"]

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "sidedish"
      POSTGRES_PASSWORD: "postgres"

  redis:
    image: redis/redis-stack
    ports:
      - "6379:6379"
